// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: inception_inference.proto
#ifndef GRPC_inception_5finference_2eproto__INCLUDED
#define GRPC_inception_5finference_2eproto__INCLUDED

#include "inception_inference.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace tensorflow {
namespace serving {

class InceptionService GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Classify(::grpc::ClientContext* context, const ::tensorflow::serving::InceptionRequest& request, ::tensorflow::serving::InceptionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::serving::InceptionResponse>> AsyncClassify(::grpc::ClientContext* context, const ::tensorflow::serving::InceptionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::serving::InceptionResponse>>(AsyncClassifyRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::serving::InceptionResponse>* AsyncClassifyRaw(::grpc::ClientContext* context, const ::tensorflow::serving::InceptionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Classify(::grpc::ClientContext* context, const ::tensorflow::serving::InceptionRequest& request, ::tensorflow::serving::InceptionResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::serving::InceptionResponse>> AsyncClassify(::grpc::ClientContext* context, const ::tensorflow::serving::InceptionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::serving::InceptionResponse>>(AsyncClassifyRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::tensorflow::serving::InceptionResponse>* AsyncClassifyRaw(::grpc::ClientContext* context, const ::tensorflow::serving::InceptionRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_Classify_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Classify(::grpc::ServerContext* context, const ::tensorflow::serving::InceptionRequest* request, ::tensorflow::serving::InceptionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Classify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(Service *service) {}
   public:
    WithAsyncMethod_Classify() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Classify() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Classify(::grpc::ServerContext* context, const ::tensorflow::serving::InceptionRequest* request, ::tensorflow::serving::InceptionResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClassify(::grpc::ServerContext* context, ::tensorflow::serving::InceptionRequest* request, ::grpc::ServerAsyncResponseWriter< ::tensorflow::serving::InceptionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Classify<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Classify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(Service *service) {}
   public:
    WithGenericMethod_Classify() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Classify() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Classify(::grpc::ServerContext* context, const ::tensorflow::serving::InceptionRequest* request, ::tensorflow::serving::InceptionResponse* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace serving
}  // namespace tensorflow


#endif  // GRPC_inception_5finference_2eproto__INCLUDED
