// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: inception_inference.proto

#include "inception_inference.pb.h"
#include "inception_inference.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace tensorflow {
namespace serving {

static const char* InceptionService_method_names[] = {
  "/tensorflow.serving.InceptionService/Classify",
};

std::unique_ptr< InceptionService::Stub> InceptionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< InceptionService::Stub> stub(new InceptionService::Stub(channel));
  return stub;
}

InceptionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Classify_(InceptionService_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InceptionService::Stub::Classify(::grpc::ClientContext* context, const ::tensorflow::serving::InceptionRequest& request, ::tensorflow::serving::InceptionResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_Classify_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::tensorflow::serving::InceptionResponse>* InceptionService::Stub::AsyncClassifyRaw(::grpc::ClientContext* context, const ::tensorflow::serving::InceptionRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::tensorflow::serving::InceptionResponse>(channel_.get(), cq, rpcmethod_Classify_, context, request);
}

InceptionService::Service::Service() {
  (void)InceptionService_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      InceptionService_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< InceptionService::Service, ::tensorflow::serving::InceptionRequest, ::tensorflow::serving::InceptionResponse>(
          std::mem_fn(&InceptionService::Service::Classify), this)));
}

InceptionService::Service::~Service() {
}

::grpc::Status InceptionService::Service::Classify(::grpc::ServerContext* context, const ::tensorflow::serving::InceptionRequest* request, ::tensorflow::serving::InceptionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace tensorflow
}  // namespace serving

